name: Execute

on:
    workflow_dispatch:
        inputs:
            manifests:
                description: 'Manifests to use'
                required: false
                default: ''

jobs:
    
    execute:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        environment: Execution
        steps:
            - uses: actions/checkout@v3
            - shell: bash
              env:
                GIT_NAME: ${{ secrets.GIT_NAME }}
                GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
              run: |
                git config --global user.name "$GIT_NAME"
                git config --global user.email "$GIT_EMAIL"
                mkdir -pm 777 /home/runner/work/_temp/_github_home/.local/share
                mkdir -pm 777 /home/runner/work/_temp/_github_home/.DepotDownloader
            - uses: docker://ghcr.io/lifeismana/cs2-vpk-decompiler-github:latest
              env:
                MANIFESTS: "${{ inputs.manifests }}"
