name: Execute

on:
    workflow_dispatch:
        inputs:
            manifests:
                description: 'Manifests to use'
                required: false
                default: ''

jobs:
    
    execute:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        environment: Execution
        concurrency:
            group: ${{ github.workflow }}
        steps:
            - name: More space
              shell: bash
              run: |
                sudo rm -rf /usr/share/dotnet
                sudo rm -rf /usr/local/lib/android
                sudo rm -rf /opt/ghc
                sudo rm -rf /opt/hostedtoolcache/CodeQL
            - uses: actions/checkout@v3
            - uses: docker://ghcr.io/lifeismana/cs2-vpk-decompiler-github:latest
              env:
                GIT_NAME: ${{ secrets.GIT_NAME }}
                GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
                MANIFESTS: "${{ inputs.manifests }}"
